//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal_Food
    {
        public int Animal_ID { get; set; }
        public Nullable<int> Breakfast_ID { get; set; }
        public Nullable<int> Amount_of_breakfast { get; set; }
        public Nullable<int> Lunch_ID { get; set; }
        public Nullable<int> Amount_of_lunch { get; set; }
        public Nullable<int> Dinner_ID { get; set; }
        public Nullable<int> Amount_of_dinner { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Food Food { get; set; }
        public virtual Food Food1 { get; set; }
        public virtual Food Food2 { get; set; }
    }
}
