//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animal()
        {
            this.Animal_Accident = new HashSet<Animal_Accident>();
            this.Animal_Cage = new HashSet<Animal_Cage>();
        }
    
        public int ID { get; set; }
        public string Vietnamese_name { get; set; }
        public Nullable<int> Species_ID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<bool> Red_list { get; set; }
        public string Sciene_name { get; set; }
        public string English_name { get; set; }
        public Nullable<int> TypeOfBirth_ID { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<System.DateTime> Date_of_joint { get; set; }
        public Nullable<int> Origin_ID { get; set; }
        public string Feature { get; set; }
        public Nullable<System.DateTime> Date_of_birth { get; set; }
        public string Picture { get; set; }
        public Nullable<int> Age { get; set; }
    
        public virtual Origin Origin { get; set; }
        public virtual Species Species { get; set; }
        public virtual TypeOfBirth TypeOfBirth { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animal_Accident> Animal_Accident { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animal_Cage> Animal_Cage { get; set; }
        public virtual Animal_Food Animal_Food { get; set; }
    }
}
