//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food_Price
    {
        public int ID { get; set; }
        public Nullable<int> Food_ID { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<System.DateTime> Applied_date { get; set; }
    
        public virtual Food Food { get; set; }
    }
}
